will-berg/assignment2

ci_server.py
tests/test_ci_server.py

resolve : #7 
Respond to ping event 
Create skeleton for test file for the CI server
Create test for responding to ping event

feat: Respond to ping event #7

---

run.sh

feat: Create script to run services

---

build.sh

fix: Specify Python 3 in commands

---

.gitignore
ci_server.py

feat: #20 created a function that sets commit status on change.

---

ci_server.py

feat: Call notify with results

---

main.yaml

feat: #22 Created github actions.

---

.github/workflows/main.yaml
build.sh

fix: Activate venv before each run

---

tests/updater.py
updater.py

fix: #25 fix updater.

---

DOCS

docs: Describe how the services interact with each other

---

ci_server.py

feat: #45 changed github api to status checks

---

updater.py

fix: #60 testing check moved.

---

test.sh

test: #42 updater file added.

---

ci_server.py

feat: #62 added commit status description

---

ci_server.py

feat: Store output data to file (#68)

---

ci_server.py

feat: Added target_url (#69)

---

ci_server.py

fix: Spawn child process to handle CI

---

ci_server.py

feat: added commit id and date on top of build file (#82)

---

ci_server.py

feat: added pending status on commit at the start of build (#83)

---

ci_server.py

fix: Changed string to bytes (#89)

---

README.md
ci_server.py
run.sh
web.py

feat: Let user set build output location

---

ci_server.py

feat: Added success or failure to the output file (#101)

---

ci_server.py

fix: Set encoding for all bytes conversions

---

tests/updater.py
updater.py

updates only on main branch

---

ci_server.py
tests/ci_server.py

test: Test for 200 status code on valid push event
